apiVersion: v1
kind: Service
metadata:
  name: {{ include "ion.fullname" . }}-biz
  labels:
    {{- include "ion.labels" . | nindent 4 }}
  annotations:
    beta.cloud.google.com/backend-config: "{\"ports\": {\"8443\":\"{{include "ion.fullname" . }}-backend\"}}"
spec:
  type: NodePort 
  ports:
  - name: biz
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "ion.name" . }}-biz
    app.kubernetes.io/instance: {{ .Release.Name }}


